### ISSUE TITLE
Does not tensor parallelism reduce memory usage per GPU?

### ISSUE THREAD

**Issue by t-hyun** [tunib-ai/oslo#151]
안녕하세요, 좋은 repo 만들어 주셔서 감사드립니다!
현재 OSLO v1.1.2를 이용해 pipeline parallel training과 tensor parallel training을 해 보았습니다.
그런데 pipeline parallel model partition을 하면 처음에 모델이 로드되었을 때 (activation이나 gradients가 없을 때) 각각 GPU에 들어가는 메모리가 거의 GPU 개수에 반비례해서 줄어드는 반면 tensor parallel을 하면 처음에 모델이 로드되었을 때 각각 GPU에 들어가는 메모리가 전혀 바뀌지 않는 것을 확인하였습니다.
예를 들어 PP stage 2, TP stage 2라 한다면 (embedding, preblock, postblock, head등을 제외하고 생각했을 때)
모델의 크기가 M이면 각 GPU에 모델이 M/4씩 들어가야 할 것 같은데 M/2씩 들어가고 있습니다.
코드를 보았을 때도 pipeline parallel engine의 경우 parallelize 단계에서 GPU로 parameter를 이동시켜 주는 반면, tensor parallel engine의 경우 비슷한 코드가 없습니다. 따라서 pipeline rank에 의해서 모델이 반씩 통째로 GPU에 들어가게 되는 것으로 판단하였습니다.
하지만 이렇다면 Tensor parallel을 이용해 '더 큰 모델'을 훈련하는 것은 불가능해지기 때문에, tensor parallel의 구현상 버그이거나 저희가 사용을 잘못하고 있는 것 같아 이렇게 issue를 올리게 되었습니다!
oslo의 tensor parallel에서 expected behavior는 무엇인지 여쭤보고 싶습니다.
감사합니다.

oslo에서 구현된 'gpt2'를 기준으로 시도해 보았습니다.
[PP stage 2, TP X]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/42180552/185540827-1c1ebf27-945c-49f5-8289-008495a73147.png">
[PP stage 2, TP stage 2] 입니다.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/42180552/185540987-ce48fffd-57cd-46c5-851a-2bee26347b6a.png">

## How to reproduce

```python
# Copyright 2021 TUNiB Inc.

import os
import random
import time
import numpy
import torch
import torch.distributed as dist
from datasets import load_dataset
from torch.utils.data import DataLoader, DistributedSampler
from transformers import GPT2Tokenizer

from oslo.models.gpt2.modeling_gpt2 import (
    GPT2ForSequenceClassification, GPT2ForTokenClassification, GPT2LMHeadModel
)
from oslo.models.gptj.modeling_gptj import (
    GPTJForCausalLM, GPTJForSequenceClassification,
)


class TestTPTraining:
    def __init__(self, num_gpus, batch_size=1, total_step=10):
        random.seed(42)
        numpy.random.seed(42)
        torch.manual_seed(42)
        self.num_gpus = num_gpus
        self.batch_size = batch_size
        self.total_step = total_step
        self.save_path = "save"
        self.tokenizer = GPT2Tokenizer.from_pretrained(
            'gpt2')
        self.tokenizer.pad_token = self.tokenizer.eos_token

    def eval_tp_for_language_modeling(self, lm_model, pretrained_model_name_or_path, pipeline_parallel_size, tensor_parallel_size):
        assert self.num_gpus == pipeline_parallel_size * tensor_parallel_size
        model_tp = lm_model.from_pretrained_with_parallel(
            pretrained_model_name_or_path,
            pipeline_parallel_size=pipeline_parallel_size,
            tensor_parallel_size=tensor_parallel_size,
        )

        time.sleep(10)
        print("sleep ended!")
        model_tp.eval()

        datasets = load_dataset("squad").data["train"]["context"]
        datasets = [str(sample)
                    for sample in datasets if len(str(sample)) < 500]
        data_loader = DataLoader(
            datasets,
            batch_size=self.batch_size,
            num_workers=8,
            shuffle=False,
            pin_memory=True,
            sampler=DistributedSampler(
                datasets,
                num_replicas=model_tp.mpu.get_data_parallel_world_size(),
                rank=model_tp.mpu.get_data_parallel_rank(),
                shuffle=False,
            ),
        )

        for i, data in enumerate(data_loader):
            tokens = self.tokenizer(
                data,
                padding=True,
                truncation=True,
                max_length=1024,
                return_tensors="pt",
            ).to("cuda")

            loss_pp = []

            for output in model_tp(
                input_ids=tokens.input_ids,
                attention_mask=tokens.attention_mask,
                labels=tokens.input_ids,
                use_cache=False,
            ):
                micro_loss = output.loss
                loss_pp.append(micro_loss.detach().item())

            loss_pp = sum(loss_pp) / len(loss_pp)

            if dist.get_rank() == 0:
                print(
                    f"{pretrained_model_name_or_path} - "
                    f"step: {i}, "
                    f"loss_pp:{loss_pp}"
                )

            if i >= self.total_step - 1:
                break

if __name__ == "__main__":
    test = TestTPTraining(num_gpus=4, batch_size=1, total_step=20)
    test.eval_tp_for_language_modeling(
        lm_model=GPT2LMHeadModel, pretrained_model_name_or_path='gpt2', pipeline_parallel_size=2, tensor_parallel_size=2) 
```

## Environment

- OS : ubuntu 18.04
- Python version : 3.8
- Transformers version : 4.20.1
- Whether to use Docker: X
- Misc.: X

**Comment by hyunwoongko** [comment]
터미널에서 보면 그렇게 보이지만 실제로는 할당된 메모리가 줄어듭니다.
OSLO 2.XX 부터는 제가 PP / TP 메모리 할당 알고리즘을 변경해서 두 메커지즘을 동시에 사용해서 할당되도록 만들었는데,
OSLO 1.XX를 만들던 당시에는 제가 그걸 떠올리지 못해서 PP먼저 하고 TP를 나중에 하도록 했었어요.

예를 들면 이런거죠. 레이어가 12개인 트랜스포머 모델이 있고 지피유가 4대 있다고 해봅시다.
그러면 다음과 같이 분할됩니다.
```
0,1,2/3,4,5/6,7,8/10,11,12
```
즉, 이때는 TP를 안하고 PP 먼저 메모리에 올렸어요. 그러고나서 PP가 끝나고나면,
각 레이어를 TP를 통해 여러조각으로 잘랐습니다. 그러면 이렇게 되겠죠.

```
0,1,2/3,4,5/6,7,8/10,11,12
0,1,2/3,4,5/6,7,8/10,11,12
```

그러면 왜 터미널에는 gpu 메모리가 저렇게 나오는걸까요?
정답은 캐싱에 있습니다. 처음에 10GB의 메모리를 지피유에 할당하고 나서 10GB 텐서를 잘라서 5GB로 만들면
NVIDIA GPU는 할당되었던 영역을 캐싱해놓습니다. 즉, 빈 공간이며, 사용할수 있는 공간이지만, 
나중에 공간자체를 다시 할당하려면 오래걸리니, 비워는 두되 저 공간을 아예 없애진 않는거죠.

지금 보시는 결과는 할당된 메모리 영역 + 캐싱된 영역을 합쳐서 보여주기에 TP 이후에도 변화가 없게 나오는것 입니다.
보다 정확한 메모리 할당영역을 보시려면 `torch.cuda.memory_allocated()`나, `torch.cuda.summary()`를 사용하시는걸 추천드립니다.
print를 찍으면 여러 지피유에서 정신없이 찍어댈테니 `torch.distributed.get_rank() == 0`에서만 보시는걸 추천드립니다.

**Comment by hyunwoongko** [comment]
참고로 OSLO 2.XX에서는 새로운 메커니즘을 도입했지만 정작 PP가 없어서 실질적인 효과는 없었고, 현재 개발중인 OSLO 3.XX은 새로운 메커니즘을 통해 초반부터 소비되는 메모리 공간을 줄이도록 구현하고있습니다.

**Comment by t-hyun** [comment]
안녕하세요, 질문에 빠르게 대답해 주셔서 정말 감사합니다!!
알려주신 대로 TP시 gpu memory가 감소하는지를 확인해 보려고 v.1.1.2 OSLO에서 PP stage 2, TP stage 2로 gpt2와 gpt2-large를 로드해보았습니다. rank 0, 1, 2, 3일 때를 각각 해 보았습니다.
코드는 oslo/parallelism_utils.py

결과는 각각 아래와 같았습니다.
gpt2 rank0
```
before PP 0
after PP 334738432
before TP 334738432
after TP 313483264
```
gpt2 rank1
gpt2 rank2
gpt2 rank3

gpt2-large rank0
gpt2-large rank1
gpt2-large rank2
gpt2-large rank3

**Comment by t-hyun** [comment]
안녕하세요, 질문에 빠르게 대답해 주셔서 정말 감사합니다!! cached GPU 생각은 하지 못했습니다. 알려주셔서 감사합니다. 그래서 말씀해주신 대로 확인해보려고 했습니다.
알려주신 대로 TP시 gpu memory가 감소하는지를 확인해 보려고 v.1.1.2 OSLO에서 PP stage 2, TP stage 2로 gpt2를 로드해보았습니다. rank 0, 1, 2, 3일 때를 각각 해 보았습니다.
코드는 `oslo/parallelism_utils.py` 내의 `_exec_both_engine`에서 `torch.cuda.memory_allocated()` 를 추가한 변형만 했습니다.
결과는 각각 아래와 같았습니다.
gpt2 모델이 548MB이니 PP 때는 대략 절반 정도로 나눠지는 것이 확인이 되었지만, TP 때 메모리가 반보다는 훨씬 덜 감소하는 것 같습니다. 저의 실험에서 무엇이 잘못되었을지 혹시 조언을 주실 수 있으실까요?
OSLO의 구조를 보면 메모리가 이렇게 나오면 안 될 것 같습니다.
tpe.parallelize() -> self._parallelize_block_layers() (또는 pre block, post block 등) -> self._column_slice() (또는 self._row_slice()) -> self._slice_layer() 까지 불리는 것을 확인하였습니다. layer의 weight들이 잘 chunk되는 것을 확인했습니다. 일부를 제외하고는 모두 tensor parallel이 될 텐데 이 실험에서 어디가 잘못된 부분이 있을까요?(self._slice_layer는 gpt2에서 모든 rank포함해 96번 불렸는데 모든 레이어가 TP되는 게 맞는 것 같습니다) reproduce용 코드는 맨 아래에 첨부하였습니다.
다시 한 번 좋은 레포 만들어 주셔서 감사합니다!
```
       if pipeline_parallel_size > 1:
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' before PP', torch.cuda.memory_allocated())
            model._exec_pipeline_engine(mpu=mpu, micro_batch_size=micro_batch_size)
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' after PP', torch.cuda.memory_allocated())

        if tensor_parallel_size > 1:
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' before TP', torch.cuda.memory_allocated())
            model._exec_tensor_engine(mpu=mpu)
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' after TP', torch.cuda.memory_allocated())
```
gpt2 rank0
```
0  before PP 0
0  after PP 334738432
0  before TP 334738432
0  after TP 313483264
PP stage:  2 TP stage:  2
```
gpt2 rank1
```
1  before PP 0
PP stage:  2 TP stage:  2
1  after PP 334738432
1  before TP 334738432
1  after TP 313483264
```
gpt2 rank2
```
2  before PP 0
PP stage:  2 TP stage:  2
2  after PP 331598848
2  before TP 331598848
2  after TP 313483264
```
gpt2 rank3
```
3  before PP 0
PP stage:  2 TP stage:  2
3  after PP 331598848
3  before TP 331598848
3  after TP 313483264
```

테스트한 코드를 아래에 첨부합니다.
```
import os
import random
import time
import numpy
import torch
import torch.distributed as dist
from datasets import load_dataset
from torch.utils.data import DataLoader, DistributedSampler
from transformers import GPT2Tokenizer

from oslo.models.gpt2.modeling_gpt2 import (
    GPT2ForSequenceClassification, GPT2ForTokenClassification, GPT2LMHeadModel
)

class TestPPTP:
    def __init__(self, num_gpus, batch_size=1, total_step=10):
        random.seed(42)
        numpy.random.seed(42)
        torch.manual_seed(42)
        self.num_gpus = num_gpus
        self.batch_size = batch_size
        self.total_step = total_step
        self.save_path = "save"
        self.tokenizer = GPT2Tokenizer.from_pretrained(
            'gpt2')
        self.tokenizer.pad_token = self.tokenizer.eos_token

    def load_tp(self, model, pretrained_model_name_or_path, pipeline_parallel_size, tensor_parallel_size):
        assert self.num_gpus == pipeline_parallel_size * tensor_parallel_size
        model_tp = model.from_pretrained_with_parallel(
            pretrained_model_name_or_path,
            pipeline_parallel_size=pipeline_parallel_size,
            tensor_parallel_size=tensor_parallel_size,
        )
        if dist.get_rank() == 0:
            print("PP stage: ", pipeline_parallel_size, "TP stage: ", tensor_parallel_size)

if __name__ == "__main__":
    test = TestPPTP(num_gpus=4)
    test.load_tp(
        model=GPT2LMHeadModel, pretrained_model_name_or_path='gpt2', pipeline_parallel_size=2, tensor_parallel_size=2)
```

**Comment by hyunwoongko** [comment]
print("PP stage: ", pipeline_parallel_size, "TP stage: ", tensor_parallel_size)
말고 print 하는 코드가 어디에 있을까요?

**Comment by t-hyun** [comment]
https://github.com/tunib-ai/oslo/blob/4b3328813f0c16bfed4b7800259327dc736b66c0/oslo/parallelism_utils.py#L231
부근에 있습니다!
다음과 같습니다.
```python
       if pipeline_parallel_size > 1:
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' before PP', torch.cuda.memory_allocated())
            model._exec_pipeline_engine(mpu=mpu, micro_batch_size=micro_batch_size)
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' after PP', torch.cuda.memory_allocated())

        if tensor_parallel_size > 1:
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' before TP', torch.cuda.memory_allocated())
            model._exec_tensor_engine(mpu=mpu)
            if dist.get_rank() == 0:
                print(dist.get_rank(), ' after TP', torch.cuda.memory_allocated())
```

**Comment by hyunwoongko** [comment]
흠 그러게요. 혹시 print 전체 torch.cuda.empty_cache() 한번 해보실수 있나요?
+ 더 큰 모델로도 실험하고 알려주시면 감사하겠습니다.

**Comment by t-hyun** [comment]
안녕하세요, torch.cuda.empty_cache()를 하고 실험한 결과입니다. 아래와 같이 매번 했습니다.
gpt2, gpt2-large, gpt-neo-1.3B에 대해 해보았는데 TP stage 2, PP stage 2로 하면 모두 같은 양상이었습니다. PP로 할 때 메모리가 반보다 살짝 덜 줄어들고 (pre block & embedding이 있으므로) TP를 더해주면 메모리가 거기서 더 줄어들기는 하지만 1/4보다 훨씬 큰 값에서 멈춥니다.
하지만 PP 없이 TP만 한다면 효과가 있습니다.
gpt2, gpt2-large 에 대해 총 GPU 8개 이내로 TP, PP를 해 본 결과를 첨부드립니다.

바꾼 코드는 아래와 같습니다.https://github.com/tunib-ai/oslo/blob/4b3328813f0c16bfed4b7800259327dc736b66c0/oslo/parallelism_utils.py#L231 부근입니다.
```python
       if pipeline_parallel_size > 1:
           torch.cuda.empty_cache()
           if dist.get_rank() == 0:
               print(dist.get_rank(), ' before PP', torch.cuda.memory_allocated())
           model._exec_pipeline_engine(mpu=mpu, micro_batch_size=micro_batch_size)
           torch.cuda.empty_cache()
           if dist.get_rank() == 0:
               print(dist.get_rank(), ' after PP', torch.cuda.memory_allocated())
       if tensor_parallel_size > 1:
           torch.cuda.empty_cache()
           if dist.get_rank() == 0:
               print(dist.get_rank(), ' before TP', torch.cuda.memory_allocated())
           model._exec_tensor_engine(mpu=mpu)
           torch.cuda.empty_cache()
           if dist.get_rank() == 0:
               print(dist.get_rank(), ' after TP', torch.cuda.memory_allocated())
       setattr(model, "initial_parameters", kwargs)
       setattr(model, "mpu", mpu)
       setattr(model.base_model, "mpu", mpu)
```
##1. 다양한 모델 PP->TP (stage 2씩)
gpt2 (355M) (* single GPU에 올라가면 511148032)
0  before PP 0
0  after PP 334738432
0  before TP 334738432
0  after TP 313483264
PP stage:  2 TP stage:  2
1  before PP 0
PP stage:  2 TP stage:  2
1  after PP 334738432
1  before TP 334738432
1  after TP 313483264
2  before PP 0
2  after PP 331598848
2  before TP 331598848
2  after TP 313483264
PP stage:  2 TP stage:  2

gpt2-large (774M) (* single GPU에 올라가면 3210018816)
0  before PP 0
0  after PP 1736600576
0  before TP 1736600576
0  after TP 1559525376
PP stage:  2 TP stage:  2
1  before PP 0
1  after PP 1736600576
1  before TP 1736600576
1  after TP 1559525376
PP stage:  2 TP stage:  2
2  before PP 0
2  after PP 1731367936
2  before TP 1731367936
2  after TP 1559525376
PP stage:  2 TP stage:  2
3  before PP 0
3  after PP 1731367936
3  before TP 1731367936
3  after TP 1559525376
PP stage:  2 TP stage:  2

EleutherAI/gpt-neo-125M (125M) (* single GPU에 올라가면 555601920)
0  before PP 0
0  after PP 358800384
0  before TP 358800384
0  after TP 358806528
PP stage:  2 TP stage:  2

EleutherAI/gpt-neo-1.3B (1.3B) (* single GPU에 올라가면 5362978816)
0  before PP 0
0  after PP 2895722496
0  before TP 2895722496
0  after TP 2895738880
1  before PP 0
1  after PP 2895722496
1  before TP 2895722496
1  after TP 2895738880
2  before PP 0
2  after PP 2878961664
2  before TP 2878961664
2  after TP 2895738880
3  before PP 0
3  after PP 2878961664
3  before TP 2878961664
3  after TP 2895738880

##2. TP, PP stage 다양하게.
gpt2 (335M) (* single GPU에 올라가면 511148032)
PP\TP | 1 | 2 | 4 | 8
-- | -- | -- | -- | --
1 |   | 269191168 | 140284928 | 77898752
2 | 334738432 | 313483264 | 304492544 |  
4 | 246536704 | 235912192 |   |  
  | 187735552 |  

gpt2-large (774M)(* single GPU에 올라가면 3210018816)
PP\TP | 1 | 2 | 4 | 8
-- | -- | -- | -- | --
1 |   | 1589009408 | 818241536 | 435762176
2 | 1736600576 | 1559525376 | 1470987264 |  
4 | 999896576 | 911364096 |   |  
8 | 590616576 |

**Comment by hyunwoongko** [comment]
배치사이즈 몇까지 학습되는지 조사해보는것도 좋을것 같아요.

**Comment by hyunwoongko** [comment]
아마 TP를 하면 액티베이션 메모리가 크게 줄어서 배치는 많이 들어갈거에요.

**Comment by t-hyun** [comment]
감사합니다! 배치 사이즈도 확인해보겠습니다.
전에 PP로 eval만 해 보았을 때 6.7B짜리 모델의 경우 8조각으로 나눠서 배치사이즈 16까지 돌아갔었는데, TP 8조각이라면 배치사이즈가 더 크게 될지도 모르겠네요. (CPU OOM을 막기 위해 수정해서 사용했지만요.) 확인해보면 좋을 것 같습니다.
그런데 TP와 PP를 동시에 사용했을 때 allocated memory가 GPU 개수에 반비례하지 않는 것은 왜일까요?

**Comment by hyunwoongko** [comment]
어차피 정확히 반비례는 안될거에요. 중복되는 영역이 있어서..
근데 지금 보여주신 수치는 생각보다 너무 적게 감소하긴 하네요. 원인은 저도 잘 모르겠습니다.
현재 코드가 아니기도 해서 분석하기도 좀 애매하네요. 3.0에선 안저럴거에요.
애초에 PP -> TP로 병렬화 하는 메커니즘 자체가 잘못되었다고 생각합니다.

**Comment by t-hyun** [comment]
그렇군요! 답변 정말 감사합니다.
혹시 3.0 전의 현재 master branch도 실행을 시켜서 PP와 TP를 활용한 훈련을 시키는 것이 가능할지요.

**Comment by hyunwoongko** [comment]
아뇨 아직이요.

**Comment by t-hyun** [comment]
issue에 답변 주셔서 정말 감사합니다. 도움이 많이 되었습니다! 아쉽네요ㅠㅠㅎㅎ
그러면 이 Issue는 닫도록 하겠습니다.

**Comment by hyunwoongko** [comment]
네 출시되면 연락한번 드릴게요! 감사합니다~

**Comment by t-hyun** [comment]
네!!! 감사합니다 :D
