### ISSUE TITLE
Where did Pipeline Parallelism go?

### ISSUE THREAD

**Issue by sdtblck** [tunib-ai/oslo#21]
In earlier commits, you had a [pipeline parallel engine](https://github.com/tunib-ai/oslo/blob/44c88b5f3d391dcb8ff4b7ad48937f2c77495401/oslo/parallelism/engine_pipeline.py#L16), but I can no longer find it in the main branch.

What's the reasoning behind rolling this back? Will it be brought back in a future version?

**Comment by hyunwoongko** [comment]
Hello @sdtblck. I have redesigned the pipeline parallelization engine to work without any code changes. It will be added and deployed to the main branch soon.

**Comment by hyunwoongko** [comment]
https://github.com/tunib-ai/oslo/issues/38
