### ISSUE TITLE
Confusion on `hidden size` and `number of heads`

### ISSUE THREAD

**Issue by sbmaruf** [tunib-ai/oslo#32]
Hi! 
Can you explain a bit more on these two line, 
https://github.com/tunib-ai/oslo/blob/master/tutorials/model_parallelism/step_2_tp_training.py#L34-L35
What do you mean by `hidden size` and `number of heads`?
Isn't `hidden size`, `number of heads` both greater than 4 (number of GPU) in gpt-2? Did you mean smaller than?

**Comment by hyunwoongko** [comment]
Oh it's mistake. I'll fix. Thank you

**Comment by hyunwoongko** [comment]
The number of heads and hidden size must be same or bigger than tp size.

**Comment by hyunwoongko** [comment]
Fixed by https://github.com/tunib-ai/oslo/pull/33/
