### ISSUE TITLE
example.py 오류

### ISSUE THREAD

**Issue by BangDaeng** [tunib-ai/oslo#5]
oslo/tests/gptj/ 경로에 있는
example script들에 .cuda()가 명시되어 있지 않아서
실행하는데 오류가 발생하는데 확인 부탁드립니다. :)
![image](https://user-images.githubusercontent.com/43260218/147429374-4a22bb64-a0ab-4db6-8332-70250c4a2e76.png)

## How to reproduce

```python
    @torch.no_grad()
    def test_gptj_lm_head_model(self, fp16):
        model_3d = GPTJForCausalLM.from_pretrained_with_parallel(
            "anton-l/gpt-j-tiny-random",
            tensor_parallel_size=self.num_gpus // 2,
            pipeline_parallel_size=self.num_gpus // 2,
            torch_dtype=torch.float16 if fp16 else torch.float32,
        ).eval()
```
```python
    @torch.no_grad()
    def test_gptj_lm_head_model(self, fp16):
        model_3d = GPTJForCausalLM.from_pretrained_with_parallel(
            "anton-l/gpt-j-tiny-random",
            tensor_parallel_size=self.num_gpus // 2,
            pipeline_parallel_size=self.num_gpus // 2,
            torch_dtype=torch.float16 if fp16 else torch.float32,
        ).eval().cuda()
```

## Environment

- OS : 우분투
- Python version : 3.7.10
- Transformers version : 4.14.1
- Whether to use Docker: no use
- Misc.:

**Comment by hyunwoongko** [comment]
cuda()를 찍으면 병렬화가 의미가 없어집니다. distributed launcher로 실행하신것 맞으신가요?

**Comment by hyunwoongko** [comment]
추가로 tests에 있는 코드들은 제가 테스트하려고 만든 코드이며, example의 개념으로 올려둔게 아닙니다.
코드 예제는 USAGE.md를 확인해주세요.

**Comment by BangDaeng** [comment]
> cuda()를 찍으면 병렬화가 의미가 없어집니다. distributed launcher로 실행하신것 맞으신가요? +) GPU는 몇대신가요?

먼저,, 인퍼런스 속도가 향상되는지 확인할려고 인퍼런스 용도로 테스트를 해보았고,,

GPU는 2대 사용하고 있습니다. 
USAGE.md에 나와있는
deepspeed --num_gpus=4 YOUR_SCRIPT.py 해당 분산 런처로 실행을 했는데 위와 같은 오류가 뜨네요..
인퍼런스 용도의 적절한 예시 스크립트가 tests외에 있을까요..?

**Comment by hyunwoongko** [comment]
GPU가 2대인데 4대로 병렬화 하시면 안되죠..

**Comment by BangDaeng** [comment]
> GPU가 2대인데 4대로 병렬화 하시면 안되죠..

아 그건 스크립트 내부도 2개로 바꾸고 명령어도 2개로 다 바꿔서 실행했어요 제가 말을 잘못했네요

**Comment by hyunwoongko** [comment]
인퍼런스 목적이시면 모델 생성부분 이외에는 변경할게 없습니다.
네 그 코드는 GPU4대에서 동작하게 만들어놓았습니다. num_gpus가 2가 되면, 

```
tensor_parallel_size=self.num_gpus // 2  <--- 1
pipeline_parallel_size=self.num_gpus // 2  <--- 1
```

가 되어서 텐서1, 파이프라인1이 되어 모델이 병렬화되지 않게 됩니다.
우선 Hugging Face Transformers 사용법은 알고 계실까요?

**Comment by hyunwoongko** [comment]
gpu 2대로 인퍼런스 병렬화를 하실 예정이시면,

```python
model = GPT2LMHeadModel.from_pretrained_with_parallel(..., tensor_parallel_size=2)
```

와 같이 생성하시고, 그 이후로는 Hugging Face Transformers와 동일하게 사용하시면 됩니다.
대신 inference 시에 distributed launcher를 쓰면 웹서버에 배포하시는건 어려울수도 있어요. 
혹시 웹서버 배포가 목적이실까요?

**Comment by BangDaeng** [comment]
> 인퍼런스 목적이시면 모델 생성부분 이외에는 변경할게 없습니다. 위의 코드는 GPU4대에서 동작하게 만들어놓았습니다. num_gpus가 2가 되면,
> 
> ```
> tensor_parallel_size=self.num_gpus // 2  <--- 1
> pipeline_parallel_size=self.num_gpus // 2  <--- 1
> ```
> 
> 가 되어서 텐서1, 파이프라인1이 되어 모델이 병렬화되지 않고 GPU에 모델이 안올라가게 됩니다. 우선 Hugging Face Transformers 사용법은 알고 계실까요?

네 사용법 인지하고 있고 말씀해주신 부분을 제가 놓치고 있었네요.. 2장이면
tensor_parallel_size=2 or pipeline_parallel_size = 1로 설정해야 하는군요

**Comment by BangDaeng** [comment]
> gpu 2대로 인퍼런스 병렬화를 하실 예정이시면,
> 
> ```python
> model = GPT2LMHeadModel.from_pretrained_with_parallel(파라미터들..., tensor_parallel_size=2)
> ```
> 
> 와 같이 생성하시고, 그 이후로는 Hugging Face Transformers와 동일하게 사용하시면 됩니다. 대신 distributed launcher를 쓰면 웹서버에 배포하시는건 어려울수도 있어요. 혹시 웹서버 배포가 목적이실까요?

네 HTTP API로 서빙하려고하는데 저도 테스트 중에  distributed 런처여서 이게 서빙이 되나 고민하고 있었습니다,, 다른 방법이 있을까요 ㅠㅠ

**Comment by hyunwoongko** [comment]
> 네 사용법 인지하고 있고 말씀해주신 부분을 제가 놓치고 있었네요.. 2장이면
   tensor_parallel_size=2 or pipeline_parallel_size = 1로 설정해야 하는군요

네 2d 병렬화 (텐서 + 파이프라인)의 경우 최소 4장의 gpu가 필요하고 데이터 병렬화까지 추가되면 최소 8장의 gpu가 필요합니다.

**Comment by hyunwoongko** [comment]
> 네 HTTP API로 서빙하려고하는데 저도 테스트 중에 distributed 런처여서 이게 서빙이 되나 고민하고 있었습니다,, 다른 방법이 있을까요 ㅠㅠ

https://github.com/tunib-ai/parallelformers
요 프로젝트는 서빙까지 고려해서 구현이 되었구요. oslo에도 배포기능이 탑재될 예정입니다만 아직 작업중입니다.

**Comment by BangDaeng** [comment]
> > 네 HTTP API로 서빙하려고하는데 저도 테스트 중에 distributed 런처여서 이게 서빙이 되나 고민하고 있었습니다,, 다른 방법이 있을까요 ㅠㅠ
> 
> https://github.com/tunib-ai/parallelformers 요 프로젝트는 서빙까지 고려해서 구현이 되었구요. oslo에도 배포기능이 탑재될 예정입니다만 아직 작업중입니다. 참고로 위 프로젝트 사용시에는 distributed launcher를 사용하지 않으셔도 됩니다.

네 transformers 라이브러리 다큐먼트를 보다가 해당 라이브러리(parallelformers) 를 먼저 테스트했었는데
GPTJForCausalLM 해당 모델은 지원을 안하는 거 같아서 oslo로 test해보고 있었습니다. 네 감사합니다 :)..

**Comment by hyunwoongko** [comment]
최근버전으로 업데이트 하시면 GPTJ 사용 가능할거에요! 추가해놨습니다.

**Comment by hyunwoongko** [comment]
테스트 해보시고 안되면 parallelformers 쪽에 이슈 남겨주세요 :)
배포에 관련해서는 아직 미개발 영역이기 때문에, 요 이슈는 클로징 하겠습니다. :)
