### ISSUE TITLE
deparallelization에서 _parallelize_from_model 호출시 인자 오류

### ISSUE THREAD

**Issue by singleheart** [tunib-ai/oslo#9]
## How to reproduce

```sh
PYTHONPATH=. python -m torch.distributed.launch --nproc_per_node 4 ./tests/gpt2/gpt2_test_3d_deparallelization.py
```

## Environment

- OS : RHEL 7.9
- Python version : 3.8.12
- Transformers version : 4.15.0
- Whether to use Docker: No
- Misc.:
실행시 아래와 같은 오류가 발생했습니다:
```
  File "/home/singleheart/oslo/oslo/parallelism_utils.py", line 412, in _parallelize_from_split_checkpoint_files
    cls._parallelize_from_model(
TypeError: _parallelize_from_model() missing 1 required positional argument: 'kwargs'
```
https://github.com/tunib-ai/oslo/blob/863bc8b30fba790d8803afe195d137d3a8ed3d0e/oslo/parallelism_utils.py#L315
`**kwargs`로 바꾸면 좋을 것 같습니다. 수정 후에는 정상적으로 합쳐집니다.
PR을 올리려다 보니 `kwargs,`가 몇 군데 더 있고 마지막 인자가 아닌 경우도 있어서 이슈만 보고 드립니다.

**Comment by hyunwoongko** [comment]
리포트 감사드립니다. 여기에서만 에러가 발생하던가요?

**Comment by singleheart** [comment]
412번째 줄에서 멎은 것 이외에 다른 곳의 에러는 확인하지 못했습니다. 315번째 줄을 수정하니 정상 작동했고요. 다만 코드상으로는 `kwargs,`가 몇 군데 더 있는데 호출할 때 `**kwargs`로 호출하는 곳도 있고 `kwargs=kwargs,`로 호출하는 곳도 있어서 검토가 필요해 보였습니다.

**Comment by hyunwoongko** [comment]
네 감사합니다. 일단 그럼 315번째 줄만 변경해서 패치하도록 하겠습니다. 감사합니다.

**Comment by hyunwoongko** [comment]
수정하였습니다. 업데이트 해보시겠어요?

**Comment by singleheart** [comment]
업데이트 후 잘 작동합니다. 감사합니다
